
services:
  opensearch-backup-manager:
    build: .
    container_name: opensearch-backup-manager
    restart: unless-stopped
    environment:
      # OpenSearch setting
      OPENSEARCH_ADDRESSES: "https://your-opensearch-host:9200"
      OPENSEARCH_USERNAME: "your-username"
      OPENSEARCH_PASSWORD: "your-password"
      OPENSEARCH_CERT_PATH: "/certs/root.crt"
      
      # S3/MinIO settings (MinIO Go Client supports all S3-compatible storages)
      # For AWS S3: leave empty or set to s3.amazonaws.com
      # For MinIO: set to minio:9000 (without https://)
      S3_ENDPOINT: "s3.amazonaws.com"
      S3_ACCESS_KEY_ID: "your-access-key"
      S3_SECRET_ACCESS_KEY: "your-secret-key"
      S3_BUCKET: "backups"
      S3_REGION: "us-east-1"
      
      # Path to configuration
      CONFIG_PATH: "/app/config/config.yaml"
      TZ: "Etc/UTC"
    
    volumes:
      # Mount configuration
      - ./config/config.yaml:/app/config/config.yaml:ro
      # Mount OpenSearch certificate
      - ./certs/root.crt:/certs/root.crt:ro
      # Directory for temporary files (optional)
      - ./tmp:/tmp/opensearch-backups
    # Logging
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

